Import('env', 'object_files')

src = [
    "Address.cc",
    "ClientRPC.cc",
    "ClientSession.cc",
    "Protocol.cc",
    "Server.cc",
    "ServerRPC.cc",
    "ThreadDispatchService.cc",
    "OpaqueServer.cc",
    "OpaqueServerRPC.cc"
]
object_files['RPC'] = env.StaticObject(src)
