Import('env', 'object_files')

src = [
]
object_files['Protocol'] = (env.StaticObject(src) +
                            env.Protobuf("Client.proto") +
                            env.Protobuf("Raft.proto") +
                            env.Protobuf("ServerStats.proto") +
                            env.Protobuf("SnapshotStats.proto") +
                            env.Protobuf("RaftLogMetadata.proto"))
