Import('env', 'object_files')

src = [
    "RaftConsensus.cc",
    "RaftConsensusInvariants.cc"
]
object_files['Raft'] = (env.StaticObject(src) +
                                 env.Protobuf("SnapshotMetadata.proto"))
