Import('env', 'object_files')

src = [
    "FilesystemUtil.cc",
    "Layout.cc",
    "Log.cc",
    "LogFactory.cc",
    "MemoryLog.cc",
    "SimpleFileLog.cc",
    "SegmentedLog.cc",
    "SnapshotFile.cc",
    "SnapshotFileFactory.cc"
]
object_files['Storage'] = (env.StaticObject(src) +
                                    env.Protobuf("SegmentedLog.proto") +
                                    env.Protobuf("SimpleFileLog.proto") +
                                    env.Protobuf("SnapshotMetadata.proto"))
